name: gigbit_flutter
description: GigBit Flutter client
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.4
  flutter_svg: ^2.0.10
  file_picker: ^8.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/platforms/



